### ISSUE TITLE
easy tidy-ups

### ISSUE THREAD

**Issue by kbuzzard** [thehottgame/TheHoTTGame#1]
Right now there is no indication as to who the authors of this game are. Furthermore right now the link for how to get started in the README is a 404. You guys should at least say who you are, and fix the link; I was going to tweet about it but I'll hold off for a bit.

**Comment by vvs-** [comment]
@kbuzzard As for the authors, you probably could refer to https://jlh18.github.io/

Disclaimer: I'm not associated with this project whatsoever, just following the links.

P.S. BTW the same page also contains the right link for the docs.
P.P.S. Seems that my comment was irrelevant as you already know all this :smile:

**Comment by Jlh18** [comment]
I've fixed the link and will soon add authors to the site once I have their permission. And yes @kbuzzard certainly knows who we are!
