### ISSUE TITLE
Completely stuck because I can't type "⊤"

### ISSUE THREAD

**Issue by jameshfisher** [thehottgame/TheHoTTGame#16]
I'm on [Quest 1](https://thehottgameguide.readthedocs.io/en/latest/0-trinitarianism/quest-1.html), where it says

> Fill the hole with ⊤, since we want zero to be even.

How do I do this? I am using [AgdaPad](https://agdapad.quasicoherent.io/).

Here's what I've tried:

* Copy-pasting -- but this web-based VM thing doesn't seem to know about my clipboard
* Typing things like "\T" -- this seems to do _something_ related to Unicode character shortcuts, but I can't tell what

How can I proceed?

**Comment by jameshfisher** [comment]
(Aside: I think this is one of many good reasons to avoid unpronouncable mathy squiggles like `⊤` and `⊥`, and stick to ASCII `True` and `False`)

**Comment by jameshfisher** [comment]
Ok, I researched it and found a way:

Type `Ctrl+x`, then `8`, then Return. It prompts you for a unicode character name. Type `down tack` and hit Return.

(Obviously this is incredibly arcane, and there must be a more usable way ...)

**Comment by jameshfisher** [comment]
(For `⊥`, instead type `up tack`)

**Comment by jameshfisher** [comment]
Aha, I figured out (by accident) that you can type `\top` and `\bot` for these - the `\` is some kind of Unicode shortcut feature, but you need to know the names `top` and `bot`.

I suggest putting these shortcut names in the tutorial wherever a new weird character appears

**Comment by jameshfisher** [comment]
Other weird ones I've discovered: `\bN` is ℕ ("blackboard N???"), `\Sigma`

**Comment by Jlh18** [comment]
hi james! Unfortunately there is a trade off between user friendliness in terms of readability and finding the symbols. 
The bottom of this page https://thehottgameguide.readthedocs.io/en/latest/getting-started/emacs-commands.html#unicode-commands will give you a (nowhere near complete) list of inputting some of these symbols. Maybe it should be linked to more frequently in the documentation/guide.

**Comment by Jlh18** [comment]
i'll add `\top` and `\Sigma` to the above list. Where in the documentation would the link be helpful?

**Comment by Jlh18** [comment]
https://agda.readthedocs.io/en/latest/tools/emacs-mode.html#keybindings here is another list of such unicode shortcuts

**Comment by jameshfisher** [comment]
Hi! Ah I missed that list - that's useful! And the list already suggests `\GS` instead of `\Sigma`.

I would suggest linking to this list from Quest 1, which I think is the first place that the player is required to type a funny symbol.

Thanks for the quick reply!

**Comment by Jlh18** [comment]
aha, i know what it is... we put this info in the 1-FundamentalGroup but not in 0-Trinitarianism. I'll change this in a bit. Thanks for pointing this out!
