### ISSUE TITLE
Make background color respect terminal setting

### ISSUE THREAD

**Issue by elfi** [thehottgame/TheHoTTGame#8]
Hello,

I successfully managed to go through the first part of installing the HoTT game, that is the installation of the Doom Emacs. However, I can hardly see anything on the screen with the default grey-ish background color. How can I set it to a darker color? The best thing would be to simply inherit the color setting from the terminal.

Thank you for your help!

**Comment by Jlh18** [comment]
that's strange that the default theme is hard to read, but here is a way to change the theme in general: there should be a hidden folder somewhere (for linux and MacOS its probably in the home directory) called `.doom.d` or something like that, and it contains a file called `config.el`. open that and add a line (or edit a preexisting line) that says `(setq doom-theme 'doom-dracula)`. This changes you theme to `doom-dracula`. You will need to do `M-x doom/reload` and `M-x doom/restart` for the changes to take place.

For more themes have a look at https://github.com/hlissner/emacs-doom-themes#additional-themes where you probably can also find out how to change specific colours.

**Comment by elfi** [comment]
Thank you. I tested the doom-dracula and other dark themes. It's slightly better than the default theme, but still on the grey-ish side of things instead of dark background color. I'm on a Mac. Judging from your response I guess something does not work as it should. Oh well. I will have to wait for Vim or VSCode port of this game :-)
